SATyr: Satyr-dir/display.c File Reference
display.c File Reference
#include "display.h"
Functions
void displayInfo (FILE *std)
void signalHandler (int signum)
void displayStat ()
void displayFinalResult (Individual *population)
void displaySolution (Individual *pop)
Function Documentation
void displayFinalResult (Individual * population) inline
displayInfo : useful to display the final result after solving this problem
Parameters
population the population we used to solve this problem
Definition at line 105 of file display.c.
References allflip, begintime, bestnumfalse, CLOCK_TICK, displaySolution(), endtime, FOUND, MAXTRY, maxtry, NUMINDIVIDUAL, SAT, signalHandler(), and UNSAT.
Referenced by main().
{
     if (FOUND == SAT) {
         printf("c |-------------------------------------------------------------------------------------|\n");
         printf("s   SATISFIABLE\n");
         displaySolution(population);
         printf("c |-------------------------------------------------------------------------------------|\n");
         printf("c | Solving Time     :   %5.4f seconds",(double)(endtime-begintime)/CLOCK_TICK);
         printf("                            |\n");
         printf("c | After                : %10llu flips",allflip);
         printf("                            |\n");
         printf("c | Generation number    : %3d",(MAXTRY-maxtry)+1);
         if((MAXTRY-maxtry)+1 == 1)
             printf("st generation   ");
         else if((MAXTRY-maxtry)+1 == 2)
             printf("nd generation   ");
         else if((MAXTRY-maxtry)+1 == 3)
             printf("rd generation   ");
         else
             printf("th generation   ");
         printf("                        |\n");
         printf("c | With                 : %4d individuals",NUMINDIVIDUAL);
         printf("                            |\n");
         printf("c \\====================================================================================/\n\n");
     }
     else if(FOUND == UNSAT) {
         printf("c |-------------------------------------------------------------------------------------|\n");
         printf("s   UNSATISFIABLE\n");
         printf("c |-------------------------------------------------------------------------------------|\n");
         printf("c | Time             :       %4.4f seconds",(double)(endtime-begintime)/CLOCK_TICK);
         printf("                        |\n");
         printf("c | After                : %10llu flips",allflip);
         printf("                            |\n");
         printf("c | Generation number    : %3d",(MAXTRY-maxtry)+1);
         if((MAXTRY-maxtry)+1 == 1)
             printf("st generation   ");
         else if((MAXTRY-maxtry)+1 == 2)
             printf("nd generation   ");
         else if((MAXTRY-maxtry)+1 == 3)
             printf("rd generation   ");
         else
             printf("th generation   ");
         printf("                        |\n");
         printf("c | With                 : %4d individuals",NUMINDIVIDUAL);
         printf("                            |\n");
         printf("c | Best solution with   :  %5d false clauses",bestnumfalse);
         printf("                        /\n");
         printf("c \\====================================================================================/\n\n");
     } else {
         signalHandler(-1);
     }
 }
void displayInfo (FILE * std) inline
displayInfo : useful to display some informations
Parameters
std the output where we will write informations
Definition at line 31 of file display.c.
References numatom, numclause, and parsingTime.
Referenced by main().
{
     fprintf(std,"\n\n");
     fprintf(std,"c This is SATyr \n");
     fprintf(std,"c Created by Valentin Montmirail, a student in computer engineering at Polytech Tours\n");
     fprintf(std,"c \n");
     fprintf(std,"c /====================================================================================\\\n");
     fprintf(std,"c | Number of Variables  :    %5d                                                     |\n",numatom);
     fprintf(std,"c | Number of Clauses    :    %5d                                                     |\n",numclause);
     fprintf(std,"c |-------------------------------------------------------------------------------------|\n");
     fprintf(std,"c | Parsing time         :   %7.3fms                                                  |\n",parsingTime);
     fprintf(std,"c |=====================================================================================|\n");
 }
void displaySolution (Individual * pop) inline
displaySolution: this function allows us to display the solution of the problem.
Parameters
pop Represents the population where one of individual is solution
Definition at line 174 of file display.c.
References struct_individual::atom, getSolution(), and numatom.
Referenced by displayFinalResult().
{
   /* We get the solution of the problem. */
   Individual* s = getSolution(pop);
   /* We start the solution with a 'v' as expected by the SAT norm. */
   printf("v ");
   /* For every variables inside the solution. */
   for(int i = 1; i < numatom+1 ; ++i) {
     /* We display the number i  when the value is true. */
     if(s->atom[i] != 0) printf("%d ",   i);
     /* We display the number -i when the value is false. */
     else                printf("%d ",-1*i);
   }
   printf("0");
   printf("\n");
 }
void displayStat () inline
displayStat : We will display every generation to see the progression.
Definition at line 87 of file display.c.
References allflip, bestnumfalse, MAXTRY, maxtry, and numresolution.
Referenced by main().
{
     printf("c | Gener : %4d | ",(MAXTRY-maxtry)+1);
     printf("best :  %3d    | ",bestnumfalse);
     printf("resolutions : %7d | ",numresolution);
     printf("flips: %7llu flips       ",allflip);
     printf(" |\n");
 }
void signalHandler (int signum) inline
signalHandler: Useful to catch the SIGINT signal in that way, we can shut down the solver and display that we don't know if the problem is SATISFIABLE or UNSATISFIABLE... The solver will so, display UNKNOWN for the state of the result.
Parameters
signum the identification number of the signal
Definition at line 58 of file display.c.
References allflip, bestnumfalse, and numatom.
Referenced by displayFinalResult(), and main().
{
     printf("\ns   INDETERMINATE\n");
     printf("v   ");
     int i = 0;
     for(i = 0; i < numatom; ++i) { printf("? "); }
     printf("0");
     printf("\n");
     printf("c |-------------------------------------------------------------------------------------|\n");
     printf("c | Time             :         ???? seconds");
     printf("                        |\n");
     printf("c | After                :    %10llu flips",allflip);
     printf("                        |\n");
     printf("c | Best solution with   :  %5d false clauses",bestnumfalse);
     printf("                        /\n");
     printf("c \\====================================================================================/\n\n");
     exit(signum);
 }