SATyr: Satyr-dir/structure.h File Reference
structure.h File Reference
#include "individual.h"
Functions
Individual * createIndividual ()
void freePopulation (Individual *pop)
void freeIndividual (Individual *i)
Individual * createPopulation ()
int delete_individual (Individual **ind)
int delete_individual2 (Individual *y)
void insert_individual (Individual *y, Individual **z)
Individual * add_individual (Individual *ind, Individual *x)
Individual * select_individual (Individual *list)
void init (Individual *ind, int first)
Function Documentation
Individual* add_individual (Individual * ind, Individual * x) inline
add_individual : copy an individual in an other list of individuals
Parameters
x the individual where we will perform a copy
ind the linked list where we will add ind
Definition at line 300 of file structure.c.
References struct_individual::atom, struct_individual::breakcount, struct_individual::clausesFalse, createIndividual(), struct_individual::makecount, struct_individual::next, numatom, numclause, struct_individual::numfalse, struct_individual::numhamming, struct_individual::numindividual, struct_individual::numtruelit, and struct_individual::wherefalse.
Referenced by select_individual().
{
     /* We will need an index for some loop. */
     int i;
     /* We will need an individual because we will create a new one. */
     Individual *p;
     /* We create the memory space for every data inside the structure. */
     p = createIndividual();
     p->numfalse = x->numfalse;
     /* We copy every clauses. */
     for(i = 0 ; i < numclause ; ++i) {
         p->clausesFalse[i] =  x->clausesFalse[i];
         p->wherefalse[i]   =  x->wherefalse[i];
         p->numtruelit[i]   =  x->numtruelit[i];
     }
     /* We copy every atoms. */
     for(i = 1 ; i < numatom+1 ; ++i) {
         p->atom[i]         = x->atom[i];
         p->breakcount[i]   = x->breakcount[i];
         p->makecount[i]    = x->makecount[i];
     }
     /* We copy the number of individual, the number of hamming, ... */
     p->numindividual = x->numindividual;
     p->numhamming    = x->numhamming;
     p->next          = ind;
     /* We return the created copy of our individual. */
     return p;
 }
Individual* createIndividual () inline
createIndividual : create and return an individual memory space
Returns
the individual memory space created and returned
Definition at line 34 of file structure.c.
References struct_individual::atom, struct_individual::breakcount, struct_individual::clausesFalse, struct_individual::makecount, struct_individual::next, numatom, numclause, struct_individual::numfalse, struct_individual::numindividual, struct_individual::numtruelit, and struct_individual::wherefalse.
Referenced by add_individual(), createPopulation(), and cross().
{
     /* We create a new individual */
     Individual* i;
     /* We allocate the good memory space. */
     i = (Individual *) malloc(sizeof(Individual));
     /* We allocate the memory for every arrays inside the structure. */
     i->clausesFalse = (int *)malloc(sizeof(int)  * (unsigned long)(numclause));
     i->makecount    = (int *)malloc(sizeof(int)  * (unsigned long)(numatom+1));
     i->breakcount   = (int *)malloc(sizeof(int)  * (unsigned long)(numatom+1));
     i->atom         = (char*)malloc(sizeof(char) * (unsigned long)(numatom+1));
     i->wherefalse   = (int *)malloc(sizeof(int)  * (unsigned long)(numclause));
     i->numtruelit   = (int *)malloc(sizeof(int)  * (unsigned long)(numclause));
     /* For now, the Individual is not linked to anyone. */
     i->next = NULL;
     /* For now, we don't know how many false clauses is unsolved by this individual. */
     i->numfalse = 0;
     /* For now, we don't know his number yet. */
     i->numindividual = -1;
     /* We return our individual who is created and allocated. */
     return i;
 }
Individual* createPopulation () inline
createPopulation : create a population of NUMINDIVIDUAL individuals
Returns
we will return the pointer on the first element of the linked list (the population)
See also
NUMINDIVIDUAL to know how many individual inside the linked list
Definition at line 120 of file structure.c.
References bestnumfalse, cardpopulation, createIndividual(), init(), struct_individual::next, struct_individual::numfalse, NUMINDIVIDUAL, struct_individual::numindividual, population, and TRUE.
Referenced by main().
{
     /* We will make a loop to create all theses individuals inside the population. */
     int i;
     /* We will create NUMINDIVIDUAL Individuals, so we need a pointer for which of them. */
     Individual* x;
     /* For every individual that we have to create. */
     for( i = 0 ; i < NUMINDIVIDUAL ; ++i) {
         /* We create it. */
         x = createIndividual();
         /* We put the good values for theses attributes. */
         x->numindividual = cardpopulation;
         // x->numhamming    = cardpopulation;
         /* We incremente this number. */
         ++cardpopulation;
         /* TRUE because it is the first initialization */
         init(x, TRUE);
         /* Insertion of the new individual in the population */
         if (i == 0) population = x;
         else {
             x->next    = population;
             population = x;
         }
         /* We save the best individual */
         if (x->numfalse <= bestnumfalse) {
             bestnumfalse = x->numfalse;
         }
     } /* end of the "for every individual" */
     /* We return the population that we just created. */
     return population;
 }
int delete_individual (Individual ** ind) inline
delete_individual : delete the older individual of the population
Parameters
ind the individual that we want to delete.
Returns
the value return by the numhamming or the function delete_individual2
Definition at line 171 of file structure.c.
References delete_individual2(), freeIndividual(), struct_individual::next, struct_individual::numhamming, and olderindividual.
Referenced by crossover_operator().
{
     /* We will need a pointer to free our individual. */
     Individual* x;
     /* the value that we want to return. */
     int i;
     if ((*ind)->numindividual == olderindividual) {
         /* We get the hamming number of this individual. */
         i = (*ind)->numhamming;
         /* It's easier to play with only one pointer than 2 ;) */
         /* And it will be useful to free this individual */
         x = *ind;
         /* We plug the linkedlist to the next. */
         (*ind) = (*ind)->next;
         /* We will free the individual X. */
         freeIndividual(x);
     } else {
         i = delete_individual2(*ind);
     }
     ++olderindividual;
     return i;
 }
int delete_individual2 (Individual * y) inline
delete_individual2 : used by delete_individual
Parameters
y the individual that we want to delete
See also
extern int delete_individual(Individual** ind)
Returns
We return numhamming if everything okay, -1 otherwise.
Definition at line 214 of file structure.c.
References freeIndividual(), struct_individual::next, struct_individual::numhamming, and olderindividual.
Referenced by delete_individual().
{
     /* We will need a pointer to delete an individual */
     Individual* x;
     /*
      * We will return -1 if something wrong happened,
      * and the numhamming of the individual before the deleted one otherwise
      */
     int i = -1;
     /* We look for the good individual inside the linked list */
     while((y->next != NULL) && ((y->next)->numindividual != olderindividual)) {
         y = y->next;
     }
     /* If we find the good individual */
     if(y->next != NULL) {
         /* We get the numhamming to return it after. */
         i = y->next->numhamming;
         x = y->next;
         /* We plug the linkedlist to detach the deleted indivudal. */
         y->next = (y->next)->next;
         /* We free the memory space of our individual */
         freeIndividual(x);
     }
     /* We return numhamming if everything okay, -1 otherwise. */
     return i;
 }
void freeIndividual (Individual * i) inline
freeIndividual : release an individual memory space
Parameters
i the individual that we want to free the memory space
Definition at line 98 of file structure.c.
References struct_individual::atom, struct_individual::breakcount, struct_individual::clausesFalse, struct_individual::makecount, struct_individual::numtruelit, and struct_individual::wherefalse.
Referenced by crossover_operator(), delete_individual(), delete_individual2(), and freePopulation().
{
     /* We release the memory for all the arrays inside the structure. */
     free(i->breakcount);
     free(i->makecount);
     free(i->atom);
     free(i->wherefalse);
     free(i->clausesFalse);
     free(i->numtruelit);
     /* We release the memory for the pointer itself. */
     free(i);
 }
void freePopulation (Individual * pop) inline
freePopulation : free all the population (all the linked list)
Parameters
pop the population where we want to free the memory space
Definition at line 69 of file structure.c.
References freeIndividual(), and struct_individual::next.
{
     /* We start with the head of the list. */
     Individual* tmp = pop;
     /* We will need another pointer. */
     Individual* tmp2 = NULL;
     /* While we didn't reach the end of the list: */
     while( tmp != NULL ) {
         /* We store the pointer. */
         tmp2 = tmp;
         /* We go to the next pointer. */
         tmp = tmp->next;
         /* We free the previous individual. */
         freeIndividual(tmp2);
     }
 }
void init (Individual * ind, int first) inline
init : initializes the benchmark structures
Parameters
ind the individual that we need to initialize
first is it the first initialisation ?
Definition at line 358 of file structure.c.
References ABS, struct_individual::atom, struct_individual::breakcount, clause, struct_individual::clausesFalse, struct_individual::makecount, numatom, numclause, struct_individual::numfalse, struct_individual::numtruelit, random, size, TRUE, and struct_individual::wherefalse.
Referenced by createPopulation(), cross(), and tabu().
{
     int i;
     int j;
     int thetruelit = 0;
     for( i = 0 ; i < numclause ; ++i) {
         ind->numtruelit[i]   = 0;
         ind->clausesFalse[i] = 0;
     }
     ind->numfalse      = 0;
     ind->makecount[0]  = 0;
     ind->breakcount[0] = 0;
     for( i = 1 ; i < numatom+1 ; ++i) {
         ind->breakcount[i] = 0;
         ind-> makecount[i] = 0;
     }
     /* Only on the first initialisation. */
     if (first == TRUE) {
         for( i = 1 ; i < numatom+1 ; ++i) {
             ind->atom[i] = (char)(random() % 2);
         }
     }
     /* Initialize breakcount and makecount in the following: */
     for( i = 0 ; i < numclause ; ++i) {
         for( j = 0 ; j < size[i] ; ++j) {
             if((clause[i][j] > 0) == ind->atom[ABS(clause[i][j])]) {
                 ++ind->numtruelit[i];
                 thetruelit = clause[i][j];
             }
         }
         if(ind->numtruelit[i] == 0) {
             ind->wherefalse[i]               = ind->numfalse;
             ind->clausesFalse[ind->numfalse] = i;
             ++ind->numfalse;
             for( j = 0 ; j < size[i] ; ++j) ++ind->makecount[ABS(clause[i][j])];
         } else {
             if (ind->numtruelit[i] == 1) ++ind->breakcount[ABS(thetruelit)];
             ind->wherefalse[i] = -1;
         }
     }
 }
void insert_individual (Individual * y, Individual ** z) inline
insert_individual : inserts an individual in a sorted population
Parameters
y the individual that we want to insert
z our linkedlist where y will be insert
Definition at line 256 of file structure.c.
References struct_individual::next, and struct_individual::numfalse.
Referenced by crossover_operator().
{
     /* We will need a temporary pointer */
     Individual * tmp;
     /* If we need to insert at the head-place (because it's a sorted population) */
     if (y->numfalse <= (*z)->numfalse) {
         y->next = *z;
         *z = y;
     } else {
         tmp = *z;
         /* We search for the good position inside the linked list. */
         while((tmp->next != NULL) && (y->numfalse >= tmp->next->numfalse)) {
             tmp = tmp->next;
         }
         /* If we insert at the end*/
         if (tmp->next == NULL) {
             y->next = NULL;
             tmp->next = y;
         } else { /* If we are in the "middle" of the linked list. */
             y->next = tmp->next;
             tmp->next = y;
         }
     }
 }
Individual* select_individual (Individual * list) inline
select_individual : able to take from a list an individual
Parameters
list the linked list where we will look
Definition at line 346 of file structure.c.
References add_individual().
Referenced by crossover_operator().
{
     return add_individual(NULL,list);
 }