SATyr: Satyr-dir/unsat.h File Reference
unsat.h File Reference
#include "structure.h"
Functions
void displayResolution (int c1, int c2, int var)
char contains (int cl, int variable)
void tryToProveUNSAT ()
int isTautology ()
int resolution (int c1, int c2, int whichVariable, int forReal)
void restart ()
void initResolutionTable ()
Function Documentation
char contains (int cl, int variable) inline
contains : This function will test if the variable is include inside the clause
Parameters
cl the clause who maybe contains the variable
variable the variable that we need to check
Returns
TRUE if the clause contains the variable, FALSE otherwise.
Definition at line 66 of file unsat.c.
References clause, FALSE, size, and TRUE.
Referenced by initResolutionTable(), and tryToProveUNSAT().
{
     int i = 0;
     for(i = 0; i < size[cl]; ++i) {
         if(clause[cl][i] == variable) return TRUE;
     }
     return FALSE;
 }
void displayResolution (int c1, int c2, int var) inline
displayResolution: useful for debug, it will display the 2 clauses choosen for the resolution, the variable used and also the result of the operation.
Parameters
c1 the first clause used for the resolution
c2 the second clause used for the resolution
var the variable to perform the resolution.
Definition at line 34 of file unsat.c.
References clause, FOUND, numclause, numresolution, size, and UNSAT.
{
     int i;
     printf("Resolution entre %d et %d sur %d\n",c1,c2,var);
     printf("C1 : ");
     for(i = 0; i < size[c1]; i++){
         printf(" %d",clause[c1][i]);
     }
     printf("\nC2 : ");
     for(i = 0; i < size[c2]; i++){
         printf(" %d",clause[c2][i]);
     }
     printf("\nRes: ");
     if(FOUND != UNSAT) {
         for(i = 0; i < size[numclause+numresolution-1]; i++){
             printf(" %d",clause[numclause+numresolution-1][i]);
         }
         printf("\n\n");
     }
 }
void initResolutionTable ()
initResolutionTable: This function will initialize our big array that will be used to know which clauses we will use for the next resolution.
Definition at line 349 of file unsat.c.
References ABS, BIG, clause, contains(), FALSE, numclause, resolution(), resolutionTable, size, and TRUE.
Referenced by main(), and restart().
{
     int i,j,k;
     int var = BIG;
     for(i = 0; i < numclause; ++i) {
         for(j = i+1; j < numclause; ++j) {
             for(k = 0; k < size[i] ; ++k) {
                 if( contains(j,-1*clause[i][k]) == TRUE) {
                     var = ABS(clause[i][k]);
                     break;
                 }
             }
             if(var == -1) {
                 resolutionTable[i][j] = BIG;
             } else {
                 resolution(i,j,var,FALSE);
             }
             resolutionTable[j][i] = resolutionTable[i][j];
             var = -1;
         }
     }
 }
int isTautology () inline
isTautology will check if the last resolution is a tautology or not. if not, then the clause is not worth it.
Returns
TRUE if the last resolution is a tautology, FALSE otherwise.
Definition at line 172 of file unsat.c.
References clause, FALSE, numclause, numresolution, size, and TRUE.
Referenced by tryToProveUNSAT().
{
     int i,j;
     int var;
     /* We will go through all the variable inside the result of our resolution. */
     for(i = 0; i < size[numclause+numresolution-1]; ++i) {
         /* We take the i-th variable */
         var = clause[numclause+numresolution-1][i];
         /* And we will check for every other variable inside the clause, if there is var and ~var */
         for(j = 0; j < size[numclause+numresolution-1]; ++j) {
             /* If (... var or ~var ... ), then the clause is a tautology, and we don't need it. */
             if(-1*var == clause[numclause+numresolution-1][j] )
                 return TRUE;
         }
     }
     /* None of the variable inside the clause creates a tautology, the clause is useful. */
     return FALSE;
 }
int resolution (int c1, int c2, int whichVariable, int forReal) inline
resoution : This function will perform the resolution rule on 2 clauses 'c1' and 'c2'
Parameters
c1 the left member of the resolution rule
c2 the right member of the resolution rule
whichVariable on which variable we will perform the resolution
forReal is a boolean to know if we will store the result of not
Returns
0 if the problem is still UNKNOWN and 1 if the problem is UNSAT At the end, 1 clause will disappear and the 2nd one will be the result of the resolution
Definition at line 207 of file unsat.c.
References ABS, clause, FOUND, numclause, numresolution, resolutionTable, size, TRUE, and UNSAT.
Referenced by initResolutionTable(), and tryToProveUNSAT().
{
     /* In the worst case, the resolution will be just an OR between c1 and c2 */
     long max = (long)(size[c1] + size[c2]);
     /* We allocate the good size for this futur resolution's result. */
     int* tmp = (int*)( malloc( sizeof(int)*(unsigned long)max));
     int i, j, k, l;
     /* boolean to know if we need to add or not the value in the result clause. */
     char toAdd = 1;
     /* we will insert the first element in the 0th place of result */
     k = 0;
     /* -------------------------------------------------- */
     /* We will, for every atom inside the C1 claude */
     for( i = 0 ; i < size[c1] ; ++i) {
         /* compare this value with every atom inside the C2 clause */
         for( j = 0 ; j < size[c2] ; ++j) {
             /* A v -A is equals to 1, so we don't need it for the resolution. */
             if( ( (clause[c1][i] == -1*clause[c2][j]) && (ABS(clause[c1][i]) == whichVariable) )) {
                     toAdd = 0;
             }
         }
         /* We go through every element inside C2, C1 is not present. */
         if(toAdd == 1) {
             /* We will so, insert it and go for the next element */
             tmp[k++] = (char)clause[c1][i];
         }
         /* We refresh the value and go for the next one. */
         toAdd = 1;
     }
     /* -------------------------------------------------- */
     /* We will, for every atom inside the C2 clause */
     for( i = 0 ; i < size[c2] ; ++i) {
         /* compare this value with every atom inside the C1 clause */
         for( j = 0 ; j < size[c1] ; ++j) {
             /* A v -A is equals to 1, so we don't need it for the resolution. */
             if( ( (clause[c2][i] == -1*clause[c1][j]) && (ABS(clause[c2][i]) == ABS(whichVariable)) ) ) {
                     toAdd = 0;
             }
         }
         /* If we considere that we still need to insert, we should if he is not already there. */
         if(toAdd == 1) {
             for(l = 0; l < (int)max ; ++l) {
                 /* This value is already inside the result, so don't need to insert it. */
                 if(tmp[l] == clause[c2][i]) toAdd = 0;
             }
         }
         /* Ok this value passes all the tests, we need to insert it in the result. */
         if(toAdd == 1) {
             /* We insert it and we k++ for the next value. */
             tmp[k++] = (char)clause[c2][i];
         }
         /* We treat this value, let's check the next one. */
         toAdd = 1;
     }
     for(i = k; i < max; ++i) {
         tmp[i] = 0;
     }
     /* -------------------------------------------------- */
     resolutionTable[c1][c2] = k;
     /* The resolution gives us the empty clause */
     if( k == 0) {
         /* The problem is so UNSAT */
         FOUND = UNSAT;
         return  1;
     }
     if(forReal == TRUE) {
         clause[numclause+numresolution] = tmp;
         size[numclause+numresolution]   = k;
         ++numresolution;
     } else {
         free(tmp);
     }
     /* -------------------------------------------------- */
     return 0;
 }
void restart () inline
restart : We did "too much" resolution and didn't find anything yet, we restart to find... We reinitialize also the resolution table
Definition at line 327 of file unsat.c.
References clause, initResolutionTable(), numclause, numresolution, and size.
Referenced by tryToProveUNSAT().
                       {
     int i = 0;
     for(i  = 0 ; i < numresolution; i++) {
         free(clause[numclause+i]);
         size[numclause+i] = 0;
     }
     numresolution = 0;
     initResolutionTable();
 }
void tryToProveUNSAT () inline
tryToProveUNSAT: This procedure will try to prove that the problem has no solution.
Definition at line 85 of file unsat.c.
References ABS, BIG, clause, contains(), FALSE, isTautology(), numclause, numresolution, random, resolution(), resolutionTable, restart(), size, and TRUE.
Referenced by main().
{
     if(random() % 100 < 1) restart();
     /* If have gone to far, we restart everything, we will not find anything in this branch... */
     if(numresolution >= numclause) {
         restart();
     }
     int c1 = -1;
     int c2 = -1;
     int i,j,k;
     int min = BIG;
     int var = -1;
     for(i = 0; i < numclause+numresolution; ++i) {
         for(j = i+1; j < numclause+numresolution; ++j) {
             if(min > resolutionTable[i][j]) {
                 c1 = i;
                 c2 = j;
                 min = resolutionTable[i][j];
             }
         }
     }
     if(c1 == -1 || c2 == -1) {
         restart();
         return ;
     }
     for(i = 0; i < size[c1] ; ++i) {
         if( contains(c2,-1*clause[c1][i]) == TRUE) {
             var = ABS(clause[c1][i]);
             break;
         }
     }
     resolution(c1,c2,var,TRUE);
     // displayResolution(c1,c2,var);
     if(isTautology() == TRUE) {
         numresolution--;
         return ;
     }
     resolutionTable[c1][c2] = BIG;
     resolutionTable[c2][c1] = BIG;
     i = numclause+numresolution-1;
     for(j = 0; j < numclause+numresolution; ++j) {
         for(k = 0; k < size[i] ; ++k) {
             if( contains(j,-1*clause[i][k]) == TRUE) {
                 var = ABS(clause[i][k]);
                 break;
             }
         }
         if(var == -1) {
             resolutionTable[i][j] = BIG;
         } else {
             resolution(i,j,var,FALSE);
         }
         resolutionTable[j][i] = resolutionTable[i][j];
         var = -1;
     }
 }